(module
 (type $0 (func (result i32)))
 (type $1 (func))
 (import "env" "memoryBase" (global $import$0 i32))
 (import "env" "memory" (memory $0 256))
 (import "env" "table" (table 0 funcref))
 (import "env" "tableBase" (global $import$3 i32))
 (import "env" "clear_screen" (func (;1;) (type $1)))
 (import "env" "f" (global funcref))
)